config-version: 2

name: "mistyral_cat_cafe"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 367437 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ dbt.cast(dbt.current_timestamp(), 'datetime') }}"
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  mistyral_cat_cafe:
    +database: analytics
    +schema: raw

models:
  mistyral_cat_cafe:
    staging:
      +materialized: view
    marts:
      +materialized: table
